"""create missing tables

Revision ID: 8ccbfd35c684
Revises: 00b0b9043b87
Create Date: 2026-02-11 19:21:27.211094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ccbfd35c684'
down_revision: Union[str, None] = '00b0b9043b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_scores',
    sa.Column('account_score_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('approved_requests', sa.Integer(), nullable=False),
    sa.Column('rejected_requests', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('UNKWOWN', 'VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'BLOCKED', name='risk_level'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_score_id')
    )
    op.create_index(op.f('ix_account_scores_account_score_id'), 'account_scores', ['account_score_id'], unique=False)
    op.create_table('advance_invoices',
    sa.Column('advance_request_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('advance_request_status', sa.Enum('REQUESTED', 'PARTIAL_APPROVED', 'APPROVED', 'REJECTED', name='advance_invoice_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('advance_request_id')
    )
    op.create_index(op.f('ix_advance_invoices_advance_request_id'), 'advance_invoices', ['advance_request_id'], unique=False)
    op.create_table('events_history',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('INVOICE', 'ADVANCE_REQUEST', 'PAYMENT', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('INVOICE_UPLOADED', 'ADVANCE_REQUESTED', 'ADVANCE_APPROVED', 'ADVANCE_REJECTED', 'MONEY_RECOVERED', 'MONEY_LOST', 'MONEY_PARTIAL_LOST', name='event_type'), nullable=False),
    sa.Column('new_status', sa.Enum('INVOICE_UPLOADED', 'ADVANCE_REQUESTED', 'ADVANCE_APPROVED', 'ADVANCE_REJECTED', 'MONEY_RECOVERED', 'MONEY_LOST', 'MONEY_PARTIAL_LOST', name='event_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metadata', sa.BigInteger(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score_changed', sa.Enum('UNKWOWN', 'VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'BLOCKED', name='risk_level'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_history_event_id'), 'events_history', ['event_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('advance_request_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('invoice_file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('advance_request_id', sa.UUID(), nullable=False),
    sa.Column('payment_status', sa.Enum('ADVANCED', 'RECOVERED', 'PARTIAL_LOST', 'LOST', name='payment_status'), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('bank_reference', sa.String(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_invoice_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_events_history_event_id'), table_name='events_history')
    op.drop_table('events_history')
    op.drop_index(op.f('ix_advance_invoices_advance_request_id'), table_name='advance_invoices')
    op.drop_table('advance_invoices')
    op.drop_index(op.f('ix_account_scores_account_score_id'), table_name='account_scores')
    op.drop_table('account_scores')
    # ### end Alembic commands ###
